INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: Pomoc dzieciom z ubogich rodzin.', 'Fundacja "Dbam o Zdrowie"');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: Pomoc wybudzaniu dzieci ze śpiączki.', 'Fundacja "A kogo"');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji życiowej.', 'Fundacja “Dla dzieci"');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: Pomoc dla osób nie posiadających miejsca zamieszkania', 'Fundacja “Bez domu”');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: pomoc w adopcji bezdomnych psów i kotów, organizacja domów tymczasowych', 'Fundacja "Tymmmczasy"');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: pomoc osobom starszym', 'Mali Bracia Ubogich');
INSERT INTO charity.institution (description, name) VALUES ('Cel i misja: organizacja akcji Szlachetna Paczka', 'Wiosna');
INSERT INTO charity.category (name) VALUES ('zabawki');
INSERT INTO charity.category (name) VALUES ('gry');
INSERT INTO charity.category (name) VALUES ('ubranka dla dzieci');
INSERT INTO charity.category (name) VALUES ('ubrania dla dorosłych');
INSERT INTO charity.category (name) VALUES ('duży sprzęt RTV AGD');
INSERT INTO charity.category (name) VALUES ('mały sprzęt RTV AGD');
INSERT INTO charity.category (name) VALUES ('sprzęt komputerowy');
INSERT INTO charity.category (name) VALUES ('artykuły papiernicze');
INSERT INTO charity.category (name) VALUES ('produkty żywnościowe suche');
INSERT INTO charity.category (name) VALUES ('artykuły dla zwierząt');
INSERT INTO charity.category (name) VALUES ('książki');
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Warszawa', null, '2020-08-01', '10:00:00', 3, null, '00-001', 1);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Kielce', null, '2020-08-02', '11:00:00', 1, null, '25-001', 1);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Ostrowiec', null, '2020-08-03', '12:30:00', 5, null, '24-400', 2);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Kraków', null, '2020-08-04', '13:00:00', 3, null, '30-001', 3);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Modlin', null, '2020-08-05', '13:30:00', 7, null, '05-100', 3);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Rembertów', null, '2020-08-06', '10:00:00', 2, null, '04-421', 4);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Warszawa', null, '2020-08-07', '11:00:00', 4, null, '00-001', 4);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Warszawa', null, '2020-08-08', '12:30:00', 7, null, '00-001', 5);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Płock', null, '2020-08-09', '13:00:00', 3, null, '09-400', 5);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Warszawa', null, '2020-08-10', '13:30:00', 1, null, '00-001', 6);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Radom', null, '2020-08-11', '12:30:00', 3, null, '26-610', 6);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Rembertów', null, '2020-08-12', '13:00:00', 5, null, '04-421', 7);
INSERT INTO charity.donation (city, pick_up_comment, pick_up_date, pick_up_time, quantity, street, zip_code, institution_id) VALUES ('Radom', null, '2020-08-13', '13:30:00', 7, null, '26-610', 7);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (1, 4);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (2, 8);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (3, 6);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (4, 3);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (5, 11);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (6, 10);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (7, 10);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (8, 11);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (9, 3);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (10, 6);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (11, 4);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (12, 9);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (13, 8);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (13, 4);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (12, 11);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (11, 11);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (10, 3);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (9, 4);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (8, 10);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (7, 10);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (6, 8);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (5, 2);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (4, 8);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (3, 6);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (2, 4);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (1, 2);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (1, 9);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (2, 6);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (3, 3);
INSERT INTO charity.donation_categories (donation_id, categories_id) VALUES (4, 11);